# Tailscale - VPN Access
# Provides secure VPN connectivity using WireGuard

version: '3.9'

services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:v1.88
    restart: unless-stopped

    # Use host network so Tailscale can manage routes and advertise subnets
    network_mode: host

    # Map only required capabilities
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    # Map the TUN device for WireGuard tunnels
    devices:
      - /dev/net/tun:/dev/net/tun

    # Persist only the Tailscale state directory
    volumes:
      - ${TS_STATE_DIR:-/data}/tailscale/state:/var/lib/tailscale
      # Example: (UGOS specific)
      # - /volume2/docker/tailscale/state:/var/lib/tailscale

    environment:
      # Load sensitive data from .env file next to this compose file
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      # Advertise your LAN subnet (adjust to your network)
      - TS_ROUTES=${TS_ROUTES:-192.168.1.0/24}
      # Accept DNS from Tailscale
      - TS_ACCEPT_DNS=${TS_ACCEPT_DNS:-true}
      # Optional: additional flags
      # - TS_EXTRA_ARGS=--advertise-exit-node

    labels:
      - "com.docker.compose.project=tailscale"
      - "description=VPN Access via Tailscale"

# Notes:
# 1. Get an auth key from: https://login.tailscale.com/admin/settings/keys
# 2. Add TS_AUTHKEY to your .env file
# 3. The state directory persists your machine key
# 4. Adjust TS_ROUTES to match your LAN subnet
# 5. Network mode 'host' is required for Tailscale
# 6. SYS_MODULE capability is needed for kernel module loading

